// Generated by CoffeeScript 1.7.1
var Connection, Db, Mongodb, Server, oid, settings;

settings = require('../setting');

Mongodb = require('mongodb');

oid = require('mongodb').ObjectID;

Db = Mongodb.Db;

Connection = Mongodb.Connection;

Server = Mongodb.Server;

module.exports = function() {
  this.db = new Db('main', new Server(settings.host, settings.port));
  this.db.open();
  this.load = function(k) {
    return false;
  };
  this.put = function() {};
  this.del = function() {};
  return this;
};
