// Generated by CoffeeScript 1.9.1
module.exports = function(grunt) {
  var _local, _remote, backFiles, ftp;
  ftp = '113.11.197.232';
  _remote = '/opt/node/';
  _local = __dirname;
  backFiles = function(nstr) {
    var i, it, len, ref, results;
    ref = nstr.split(',');
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      it = ref[i];
      results.push({
        expand: true,
        cwd: it,
        src: ['*.js', '*.json'],
        dest: _remote + ("" + (it === './' ? '' : it))
      });
    }
    return results;
  };
  require("load-grunt-config")(grunt);
  grunt.registerTask('default', function() {
    return grunt.initConfig({});
  });
  return grunt.registerTask('su', function() {
    grunt.config.init({
      ftpscript: {
        server: {
          options: {
            host: ftp
          },
          files: backFiles('./,views,routes,model,i18n,controller,bin')
        }
      }
    });
    return grunt.task.run("ftpscript:server");
  });
};
