// Generated by CoffeeScript 1.9.1
var _code, _db, async, dao, data;

async = require('async');

_db = 'main';

_db = 'salsa';

_code = '';

process.argv.forEach(function(val, index, array) {
  return _code = array[2];
});

app = {};
log = console.log;
oid = require('mongodb').ObjectID;
code = _code;
;

dao = new require('./model/dao')(_db);

data = require("./public/module/" + code + "/data");

setTimeout(function() {
  var k, ref, v;
  dao.save(_db, 'community:code', data.community);
  ref = data.data;
  for (k in ref) {
    v = ref[k];
    dao.save(code, k, v, function() {
      return log(code);
    });
  }
  return setTimeout(function() {
    return dao.close();
  }, 3000);
}, 500);
