// Generated by CoffeeScript 1.9.1
module.exports = {
  cookieSecret: 'eclub',
  upload_path: '/opt/s.encorner.org/',
  res_Path: 'http://s.encorner.org/',
  log_path: '/opt/s.encorner.org/log/',
  db: 'after',
  host: '127.0.0.1',
  port: 27017,
  hk: {
    user: 'web',
    psd: 'travel',
    db: 'heroku_app35547637',
    port: '61371',
    host: 'ds061371.mongolab.com'
  }
};
