// Generated by CoffeeScript 1.9.1
module.exports = {
  db: 'main',
  host: '127.0.0.1',
  port: 27017,
  cookieSecret: 'eclub',
  upload_path: '/opt/node/public',
  res_path: 'http://s.wikibeijing.com/',
  log_path: '/opt/node/public/log/'
};
