// Generated by CoffeeScript 1.7.1
module.exports = {
  crumb: function(m, text) {
    var str;
    return str = "<div id=\"crumb\"><ul class=\"breadcrumb\"><li>${icon('home')} <a href=\"/index.html\">首页</a></li>";
  },
  b3Menu: function(res) {
    var str;
    return str = '';
  },
  resPath: function(code, path) {
    return _resPath + 'upload/' + code + '/' + path;
  },
  crumbItem: function(items) {
    return [
      {
        label: '首页',
        href: '/'
      }
    ].concat(items);
  }
};
