// Generated by CoffeeScript 1.9.1
module.exports = {
  crumb: function(m, text) {
    var str;
    return str = "<div id=\"crumb\"><ul class=\"breadcrumb\"><li>${icon('home')} <a href=\"/index.html\">首页</a></li>";
  },
  b3Menu: function(res) {
    var str;
    return str = '';
  },
  resPath: function(code, path) {
    return _resPath + 'upload/' + code + '/' + path;
  },
  navPage: function(code, it) {
    if (app.env) {
      return "/p/" + code + "/sight/" + it._id;
    } else {
      return "/p/sight/" + it._id;
    }
  },
  crumbItem: function(items) {
    return [
      {
        label: '首页',
        href: '/'
      }
    ].concat(items);
  }
};
