// Generated by CoffeeScript 1.9.2
var _, util;

_ = require('underscore');

util = {
  d: function(it, p) {
    var rs;
    rs = it[p];
    delete it[p];
    return rs;
  },
  r: function(it, extra) {
    if (_.isArray(it)) {
      return {
        entities: it,
        count: extra
      };
    } else if (it) {
      return {
        entity: it
      };
    }
  },
  randomInt: function(low, high) {
    return Math.floor(Math.random() * (high - low + 1) + low);
  }
};

module.exports = util;
