// Generated by CoffeeScript 1.7.1
var resetId, util, _;

_ = require('underscore');

resetId = function(it) {
  return it.id = it._id;
};

util = {
  d: function(it, p) {
    var rs;
    rs = it[p];
    delete it[p];
    return rs;
  },
  r: function(it, extra) {
    var item, _i, _len;
    if (_.isArray(it)) {
      for (_i = 0, _len = it.length; _i < _len; _i++) {
        item = it[_i];
        resetId(item);
      }
      return {
        entities: it,
        count: extra
      };
    } else if (it) {
      resetId(it);
      return {
        entity: it,
        msg: extra || 'ok'
      };
    }
  }
};

module.exports = util;
