// Generated by CoffeeScript 1.9.1
module.exports = {
  img: function(path) {
    var id;
    id = randomChar(4);
    return "<div id=\"" + id + "\" class=\"" + (cls || '') + "\" src=\"" + path + "\"\npop=\"" + (pop || false) + "\" style=\"background:url(" + this.rPath + "/img/loading-bk.gif) no-repeat 50% 50%\">loading...</div>";
  },
  link: function(name, it, cls) {
    return "<a href='/" + name + "/" + it.id + "' title='" + it.title + "' class='" + (cls || '') + "'>" + it.title + "</a>";
  },
  resPath: function(code, path) {
    return _resPath + 'upload/' + code + '/' + path;
  },
  navPage: function(code, it) {
    return "/sight/" + it._id;
  },
  crumbItem: function(items) {
    return [
      {
        label: '首页',
        href: '/'
      }
    ].concat(items);
  }
};
