// Generated by CoffeeScript 1.9.3
var auth, checkPage, checkPagePattern, ck, data, page, path, pre, router, up, wt;

router = require('express').Router();

path = require('path');

auth = require('../controller/auth');

data = require('../controller/data');

page = require('../controller/page');

up = require('../controller/upload');

checkPagePattern = function(req, rsp, next, page) {
  if (/^\w+$/.test(page)) {
    return next();
  } else {
    return rsp.end('name error');
  }
};

router.param('entity', checkPagePattern);

router.param('page', checkPagePattern);

ck = function(req) {
  return req.hostname + req.url;
};

pre = function(req, rsp, next) {
  var cc, k, opt;
  if (!app.env) {
    req.hostname = req.get('Host');
  }
  cc = req.query._c;
  if (cc) {
    if (cc === '0' && req.query._e) {
      opt = {
        $regex: {
          k: "" + req.query._e
        }
      };
    } else if (cc === '1') {
      req.url = req.url.replace('&_c=1', '');
      req.url = req.url.replace('?_c=1', '');
      opt = {
        k: ck(req)
      };
    }
    if (opt) {
      dao.delItem(_mdb, 'cache', opt, function(res) {
        return log('del...');
      });
    }
  }
  k = ck(req);
  return dao.get(_mdb, 'cache', {
    k: k
  }, function(res) {
    if (res && !app.env) {
      return rsp.end(res.str);
    } else {
      req.c = app._community[req.hostname];
      req.k = k;
      return next();
    }
  });
};

checkPage = function(req, rsp, next) {
  var pm;
  pm = req.params;
  page = pm.page || pm.entity || 'index';
  if (page === 'a' || page === 'r') {
    next();
    return;
  }
  req.fp = path.join(_path, "views/module/" + req.c.code);
  if (page === 'res' || page === 'images') {
    rsp.end('no page');
    return;
  }
  if (fs.existsSync(req.fp + "/" + page + ".jade")) {
    return next();
  } else {
    req.fp = path.join(_path, "views");
    log(req.fp + "/" + page + ".jade");
    if (fs.existsSync(req.fp + "/" + page + ".jade")) {
      return next();
    } else {
      return rsp.end('no page');
    }
  }
};

router.get('/', pre);

router.all('/a/*', pre);

router.all('/r/*', pre);

router.post('/a/upload', up.upload);

router.post('/a/upload/remove', up.remove);

router.post('/a/cleanCache', data.cleanCache);

router.post('/a/auth/login', auth.login);

router.post('/a/auth/loginByWoid', auth.loginByWoid);

router.post('/a/auth/logout', auth.logout);

router.post('/a/auth/logoutByWoid', auth.logoutByWoid);

wt = require('../controller/wechat');

router.post('/a/wt/createMenu', wt.createMenu);

router.post('/a/wt/createLimitQRCode', wt.createLimitQRCode);

router.post('/a/wt/showQRCodeURL', wt.showQRCodeURL);

router.post('/a/wt/uploadNews', wt.uploadNews);

router.get('/a/wt/userInfoByCode', wt.userInfoByCode);

router.get('/r/:entity', data.list);

router.get('/r/:entity/:id', data.get);

router.get('/r/:entity/:key/:val', data.getByKey);

router.put('/r/:entity/:id', data.edit);

router.post('/r/:entity', data.save);

router["delete"]('/r/:entity/:id', data.del);

router.get('/:entity/:attr/:id', pre);

router.get('/:entity/:attr/:id', checkPage);

router.get('/:entity/:id', pre);

router.get('/:entity/:id', checkPage);

router.get('/:page', pre);

router.get('/:page', checkPage);

router.get('/', checkPage);

router.get('/', page.page);

router.get('/:page', page.page);

router.get('/:entity/:id', page.entity);

router.get('/:entity/:attr/:id', page.entity);

module.exports = router;
