// Generated by CoffeeScript 1.9.3
var _i;

_i = {};

module.exports = function(langs) {
  if (langs == null) {
    langs = {};
  }
  this._i = _i = langs;
  _.extend(this, require('../ext/i18n'));
  return this;
};
