// Generated by CoffeeScript 1.9.1
var _, async, authController, checkType;

_ = require('underscore');

async = require('async');

checkType = function(k) {
  if (/\S+@\S+\.\S+/.test(k)) {
    return {
      email: k
    };
  } else if (/^(13[0-9]|15[0|1|2|3|6|7|8|9]|18[5|6|8|9])\d{8}$/.test(k)) {
    return {
      phone: k
    };
  } else {
    return {
      username: k
    };
  }
};

authController = {
  login: function(req, rsp) {
    var code, opt;
    code = req.c.code;
    opt = checkType(req.body.username);
    return dao.get(code, 'user', opt, function(user) {
      if (!user) {
        rsp.status(300).send({
          msg: 'm.login_f'
        });
        return;
      }
      if (user.psd !== req.body.psd) {
        return rsp.status(301).send({
          msg: 'm.login_f'
        });
      } else {
        delete user.password;
        return dao.find(code, 'membership', {
          uid: user._id
        }, {}, function(ms) {
          var it;
          opt = {
            _id: {
              $in: (function() {
                var i, len, results;
                results = [];
                for (i = 0, len = ms.length; i < len; i++) {
                  it = ms[i];
                  results.push(it.rid);
                }
                return results;
              })()
            }
          };
          return dao.find(code, 'role', opt, {}, function(rs) {
            var i, len, r, role;
            user.roles = (function() {
              var i, len, results;
              results = [];
              for (i = 0, len = rs.length; i < len; i++) {
                r = rs[i];
                results.push({
                  title: r.title,
                  label: r.label
                });
              }
              return results;
            })();
            for (i = 0, len = rs.length; i < len; i++) {
              role = rs[i];
              _.extend(user, role.res);
            }
            return rsp.send({
              user: user,
              msg: 'm.login_s'
            });
          });
        });
      }
    });
  },
  logout: function(req, rsp) {
    return rsp.send({
      msg: 'm.logout_s'
    });
  }
};

module.exports = authController;
