// Generated by CoffeeScript 1.7.1
var async, authController, checkType, _;

_ = require('underscore');

async = require('async');

checkType = function(k) {
  if (/\S+@\S+\.\S+/.test(k)) {
    return {
      email: k
    };
  } else if (/^(13[0-9]|15[0|1|2|3|6|7|8|9]|18[5|6|8|9])\d{8}$/.test(k)) {
    return {
      phone: k
    };
  } else {
    return {
      username: k
    };
  }
};

authController = {
  login: function(req, rsp) {
    var code, opt;
    code = req.params.code;
    opt = checkType(req.body.username);
    log(opt);
    return dao.get(code, 'user', opt, function(user) {
      if (!user) {
        rsp.status(300).send({
          msg: 'm.login_f'
        });
        return;
      }
      if (user.psd !== req.body.psd) {
        return rsp.status(301).send({
          msg: 'm.login_f'
        });
      } else {
        delete user.password;
        return dao.find(code, 'membership', {
          uid: user._id
        }, {}, function(ms) {
          var it;
          opt = {
            _id: {
              $in: (function() {
                var _i, _len, _results;
                _results = [];
                for (_i = 0, _len = ms.length; _i < _len; _i++) {
                  it = ms[_i];
                  _results.push(it.rid);
                }
                return _results;
              })()
            }
          };
          return dao.find(code, 'role', opt, {}, function(rs) {
            var r, role, _i, _len;
            user.roles = (function() {
              var _i, _len, _results;
              _results = [];
              for (_i = 0, _len = rs.length; _i < _len; _i++) {
                r = rs[_i];
                _results.push({
                  title: r.title,
                  label: r.label
                });
              }
              return _results;
            })();
            for (_i = 0, _len = rs.length; _i < _len; _i++) {
              role = rs[_i];
              _.extend(user, role.res);
            }
            return rsp.send({
              user: user,
              msg: 'm.login_s'
            });
          });
        });
      }
    });
  },
  logout: function(req, rsp) {
    return rsp.send({
      msg: 'm.logout_s'
    });
  }
};

module.exports = authController;
