// Generated by CoffeeScript 1.9.1
var WechatAPI, api;

WechatAPI = require('wechat-api');

api = new WechatAPI(appid, appsecret);

module.exports = {
  uploadMenus: function(req, rsp) {
    return api.createMenu(req.body.menu, function(err, res) {
      return rsp.send(res);
    });
  }
};
